import { AuthOptionDefinition, ChannelFieldDefinition, SelectOptionDefinition } from './types';

const selectOption = (value: string, label: string, labelZh: string): SelectOptionDefinition => ({
  value,
  label,
  labelZh,
});

const field = (
  id: string,
  label: string,
  labelZh: string,
  placeholder: string,
  required: boolean = false,
  secret: boolean = false,
  inputType: ChannelFieldDefinition['inputType'] = 'text',
  options?: SelectOptionDefinition[],
  help?: string,
  helpZh?: string,
): ChannelFieldDefinition => ({
  id,
  label,
  labelZh,
  placeholder,
  required,
  secret,
  inputType,
  options,
  help,
  helpZh,
});

const compatibilityOptions = [
  selectOption('openai', 'OpenAI-compatible', 'OpenAI 兼容'),
  selectOption('anthropic', 'Anthropic-compatible', 'Anthropic 兼容'),
];

export const AUTH_CATALOG: AuthOptionDefinition[] = [
  {
    id: 'openai-api-key',
    label: 'OpenAI',
    labelZh: 'OpenAI',
    description: 'Official OpenAI API key flow.',
    descriptionZh: '官方 OpenAI API Key 流程。',
    providerId: 'openai',
    probeProvider: 'openai',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--openai-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'sk-...', true, true, 'password')],
  },
  {
    id: 'anthropic-api-key',
    label: 'Anthropic',
    labelZh: 'Anthropic',
    description: 'Official Anthropic API key flow.',
    descriptionZh: '官方 Anthropic API Key 流程。',
    providerId: 'anthropic',
    probeProvider: 'anthropic',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--anthropic-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'sk-ant-...', true, true, 'password')],
  },
  {
    id: 'gemini-api-key',
    label: 'Google Gemini',
    labelZh: 'Google Gemini',
    description: 'Use Gemini API key auth.',
    descriptionZh: '通过 Gemini API Key 认证。',
    providerId: 'google',
    probeProvider: 'google',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--gemini-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'AIza...', true, true, 'password')],
  },
  {
    id: 'openrouter-api-key',
    label: 'OpenRouter',
    labelZh: 'OpenRouter',
    description: 'Use OpenRouter API key auth.',
    descriptionZh: '通过 OpenRouter API Key 认证。',
    providerId: 'openrouter',
    probeProvider: 'openrouter',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--openrouter-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'sk-or-...', true, true, 'password')],
  },
  {
    id: 'mistral-api-key',
    label: 'Mistral',
    labelZh: 'Mistral',
    description: 'Use Mistral API key auth.',
    descriptionZh: '通过 Mistral API Key 认证。',
    providerId: 'mistral',
    probeProvider: 'mistral',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--mistral-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'mistral-...', true, true, 'password')],
  },
  {
    id: 'moonshot-api-key',
    label: 'Moonshot / Kimi',
    labelZh: 'Moonshot / Kimi',
    description: 'Use Moonshot API key auth.',
    descriptionZh: '通过 Moonshot API Key 认证。',
    providerId: 'moonshot',
    probeProvider: 'moonshot',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--moonshot-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'sk-...', true, true, 'password')],
  },
  {
    id: 'minimax-api',
    label: 'MiniMax',
    labelZh: 'MiniMax',
    description: 'Use MiniMax API key auth.',
    descriptionZh: '通过 MiniMax API Key 认证。',
    providerId: 'minimax',
    probeProvider: 'minimax',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--minimax-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'minimax-...', true, true, 'password')],
  },
  {
    id: 'xai-api-key',
    label: 'xAI',
    labelZh: 'xAI',
    description: 'Use xAI API key auth.',
    descriptionZh: '通过 xAI API Key 认证。',
    providerId: 'xai',
    probeProvider: 'xai',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--xai-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'xai-...', true, true, 'password')],
  },
  {
    id: 'zai-api-key',
    label: 'Z.AI',
    labelZh: 'Z.AI',
    description: 'Use Z.AI API key auth.',
    descriptionZh: '通过 Z.AI API Key 认证。',
    providerId: 'zai',
    probeProvider: 'zai',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--zai-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'zai-...', true, true, 'password')],
  },
  {
    id: 'qianfan-api-key',
    label: 'Qianfan',
    labelZh: '千帆',
    description: 'Use Qianfan API key auth.',
    descriptionZh: '通过千帆 API Key 认证。',
    providerId: 'qianfan',
    probeProvider: 'qianfan',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--qianfan-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'qianfan-...', true, true, 'password')],
  },
  {
    id: 'volcengine-api-key',
    label: 'Volcengine',
    labelZh: '火山引擎',
    description: 'Use Volcano Engine API key auth.',
    descriptionZh: '通过火山引擎 API Key 认证。',
    providerId: 'volcengine',
    probeProvider: 'volcengine',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--volcengine-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 've-...', true, true, 'password')],
  },
  {
    id: 'byteplus-api-key',
    label: 'BytePlus',
    labelZh: 'BytePlus',
    description: 'Use BytePlus API key auth.',
    descriptionZh: '通过 BytePlus API Key 认证。',
    providerId: 'byteplus',
    probeProvider: 'byteplus',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--byteplus-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'bp-...', true, true, 'password')],
  },
  {
    id: 'kilocode-api-key',
    label: 'Kilo Gateway',
    labelZh: 'Kilo Gateway',
    description: 'Use Kilo Gateway API key auth.',
    descriptionZh: '通过 Kilo Gateway API Key 认证。',
    providerId: 'kilocode',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--kilocode-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'kilo-...', true, true, 'password')],
  },
  {
    id: 'ai-gateway-api-key',
    label: 'Vercel AI Gateway',
    labelZh: 'Vercel AI Gateway',
    description: 'Use Vercel AI Gateway API key auth.',
    descriptionZh: '通过 Vercel AI Gateway API Key 认证。',
    providerId: 'ai-gateway',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--ai-gateway-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'agw-...', true, true, 'password')],
  },
  {
    id: 'cloudflare-ai-gateway-api-key',
    label: 'Cloudflare AI Gateway',
    labelZh: 'Cloudflare AI Gateway',
    description: 'Use Cloudflare AI Gateway credentials.',
    descriptionZh: '通过 Cloudflare AI Gateway 凭证认证。',
    providerId: 'cloudflare-ai-gateway',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--cloudflare-ai-gateway-api-key',
      accountId: '--cloudflare-ai-gateway-account-id',
      gatewayId: '--cloudflare-ai-gateway-gateway-id',
    },
    fields: [
      field('apiKey', 'API key', 'API 密钥', 'cf-...', true, true, 'password'),
      field('accountId', 'Account ID', 'Account ID', 'Cloudflare account id', true),
      field('gatewayId', 'Gateway ID', 'Gateway ID', 'Gateway slug or id', true),
    ],
  },
  {
    id: 'opencode-zen',
    label: 'OpenCode Zen',
    labelZh: 'OpenCode Zen',
    description: 'Use OpenCode Zen API key auth.',
    descriptionZh: '通过 OpenCode Zen API Key 认证。',
    providerId: 'opencode-zen',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--opencode-zen-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'ocz-...', true, true, 'password')],
  },
  {
    id: 'xiaomi-api-key',
    label: 'Xiaomi',
    labelZh: '小米',
    description: 'Use Xiaomi API key auth.',
    descriptionZh: '通过小米 API Key 认证。',
    providerId: 'xiaomi',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--xiaomi-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'xiaomi-...', true, true, 'password')],
  },
  {
    id: 'synthetic-api-key',
    label: 'Synthetic',
    labelZh: 'Synthetic',
    description: 'Use Synthetic API key auth.',
    descriptionZh: '通过 Synthetic API Key 认证。',
    providerId: 'synthetic',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--synthetic-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'synthetic-...', true, true, 'password')],
  },
  {
    id: 'together-api-key',
    label: 'Together AI',
    labelZh: 'Together AI',
    description: 'Use Together AI API key auth.',
    descriptionZh: '通过 Together AI API Key 认证。',
    providerId: 'together',
    probeProvider: 'together',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--together-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'together-...', true, true, 'password')],
  },
  {
    id: 'huggingface-api-key',
    label: 'Hugging Face',
    labelZh: 'Hugging Face',
    description: 'Use Hugging Face token auth.',
    descriptionZh: '通过 Hugging Face Token 认证。',
    providerId: 'huggingface',
    probeProvider: 'huggingface',
    probeMode: 'probe',
    fieldFlagMap: {
      apiKey: '--huggingface-api-key',
    },
    fields: [field('apiKey', 'HF token', 'HF Token', 'hf_...', true, true, 'password')],
  },
  {
    id: 'venice-api-key',
    label: 'Venice',
    labelZh: 'Venice',
    description: 'Use Venice API key auth.',
    descriptionZh: '通过 Venice API Key 认证。',
    providerId: 'venice',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--venice-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'venice-...', true, true, 'password')],
  },
  {
    id: 'litellm-api-key',
    label: 'LiteLLM',
    labelZh: 'LiteLLM',
    description: 'Use LiteLLM API key auth.',
    descriptionZh: '通过 LiteLLM API Key 认证。',
    providerId: 'litellm',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--litellm-api-key',
    },
    fields: [field('apiKey', 'API key', 'API 密钥', 'litellm-...', true, true, 'password')],
  },
  {
    id: 'custom-api-key',
    label: 'Custom OpenAI/Anthropic-compatible',
    labelZh: '自定义 OpenAI/Anthropic 兼容服务',
    description: 'Use the official custom provider flow with explicit base URL and model.',
    descriptionZh: '通过官方 custom provider 流程接入，显式填写 base URL 和 model。',
    providerId: 'custom',
    probeMode: 'stage-only',
    fieldFlagMap: {
      apiKey: '--custom-api-key',
      baseUrl: '--custom-base-url',
      compatibility: '--custom-compatibility',
      modelId: '--custom-model-id',
      providerId: '--custom-provider-id',
    },
    fields: [
      field('baseUrl', 'Base URL', 'Base URL', 'https://example.com/v1', true),
      field('modelId', 'Model ID', '模型 ID', 'gpt-4.1-mini', true),
      field('compatibility', 'Compatibility', '兼容模式', '', true, false, 'select', compatibilityOptions),
      field('providerId', 'Provider ID', 'Provider ID', 'my-provider'),
      field('apiKey', 'API key', 'API 密钥', 'optional for public endpoints', false, true, 'password'),
    ],
  },
];

export const AUTH_LOOKUP = Object.fromEntries(
  AUTH_CATALOG.map((option) => [option.id, option])
) as Record<string, AuthOptionDefinition>;

export const getAuthLabel = (choice: string, language: string) => {
  const option = AUTH_LOOKUP[choice];
  if (!option) return choice;
  return language.startsWith('zh') ? option.labelZh : option.label;
};
